# Generated by Django 3.0.2 on 2020-02-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Error_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err', models.CharField(max_length=7)),
                ('used_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incrementer.Num')),
            ],
        ),
    ]
