# Generated by Django 3.0.2 on 2020-02-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incrementer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error_log',
            old_name='used_num',
            new_name='number',
        ),
    ]
