# Generated by Django 3.0.2 on 2020-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incrementer', '0002_auto_20200202_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='error_log',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=None),
            preserve_default=False,
        ),
    ]
