# Generated by Django 3.0.3 on 2020-02-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incrementer', '0003_error_log_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='num',
            name='id',
        ),
        migrations.AlterField(
            model_name='num',
            name='num',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
